import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import type { MachineGraph } from '../types';
import { renderMermaid } from './mermaid';

const CROSS_STATE_KEY = '*';

const escapeHtml = (text: string) =>
  text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const readMermaidRuntime = () => {
  const resolve = createRequire(import.meta.url).resolve;
  return readFileSync(resolve('mermaid/dist/mermaid.min.js'), 'utf8').replace(
    /<\/script/gi,
    '<\\/script',
  );
};

const renderTransitionRows = (graph: MachineGraph) =>
  graph.states
    .flatMap(state =>
      state.transitions.map(transition => {
        const from =
          state.name === CROSS_STATE_KEY
            ? '<em>any state</em>'
            : escapeHtml(state.name);
        return `        <tr>
          <td>${from}</td>
          <td><code>${escapeHtml(transition.event)}</code></td>
          <td>${transition.payload === null ? '<span class="muted">—</span>' : `<code>${escapeHtml(transition.payload)}</code>`}</td>
          <td>${transition.targets.map(target => `<code>${escapeHtml(target)}</code>`).join(' | ')}</td>
        </tr>`;
      }),
    )
    .join('\n');

const renderTerminalStates = (graph: MachineGraph) => {
  const terminal = graph.states
    .filter(state => state.name !== CROSS_STATE_KEY)
    .filter(state => state.transitions.length === 0);
  if (terminal.length === 0) return '';
  return `      <p class="muted">No outgoing events: ${terminal
    .map(state => `<code>${escapeHtml(state.name)}</code>`)
    .join(', ')}</p>`;
};

const renderMachineSection = (
  graph: MachineGraph,
) => `    <section id="${escapeHtml(graph.name)}">
      <h2>${escapeHtml(graph.name)}</h2>
      <p class="muted">${escapeHtml(graph.sourceFile)}</p>
      <pre class="mermaid">${escapeHtml(renderMermaid(graph))}</pre>
${renderTerminalStates(graph)}
      <table>
        <thead>
          <tr><th>State</th><th>Event</th><th>Payload</th><th>Targets</th></tr>
        </thead>
        <tbody>
${renderTransitionRows(graph)}
        </tbody>
      </table>
    </section>`;

const STYLES = `    :root {
      color-scheme: light dark;
      --background: #ffffff;
      --foreground: #16181d;
      --muted: #5c6370;
      --border: #e2e5ea;
      --surface: #f6f7f9;
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --background: #14161a;
        --foreground: #e7e9ee;
        --muted: #9aa1ad;
        --border: #2a2e36;
        --surface: #1c1f25;
      }
    }
    body {
      margin: 0 auto;
      padding: 2rem 1.5rem 4rem;
      max-width: 60rem;
      background: var(--background);
      color: var(--foreground);
      font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;
      line-height: 1.5;
    }
    h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
    h2 { font-size: 1.15rem; margin-bottom: 0.25rem; }
    section { margin-top: 3rem; }
    nav a { margin-right: 1rem; }
    .muted { color: var(--muted); font-size: 0.9rem; margin-top: 0; }
    .mermaid svg { max-width: 100%; height: auto; }
    .mermaid {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 0.5rem;
      padding: 1rem;
      overflow-x: auto;
      text-align: center;
    }
    table { border-collapse: collapse; width: 100%; margin-top: 1rem; display: block; overflow-x: auto; }
    th, td { border-bottom: 1px solid var(--border); padding: 0.4rem 0.6rem; text-align: left; vertical-align: top; }
    th { font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); }
    code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.85em; }`;

export const renderHtml = (graphs: MachineGraph[]) => {
  const navigation =
    graphs.length > 1
      ? `    <nav>${graphs
          .map(
            graph =>
              `<a href="#${escapeHtml(graph.name)}">${escapeHtml(graph.name)}</a>`,
          )
          .join('')}</nav>`
      : '';

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>simply-stated diagrams</title>
  <style>
${STYLES}
  </style>
</head>
<body>
  <main>
    <h1>State machines</h1>
    <p class="muted">${graphs.length} machine${graphs.length === 1 ? '' : 's'} · generated by simply-stated-diagram</p>
${navigation}
${graphs.map(renderMachineSection).join('\n')}
  </main>
  <script>${readMermaidRuntime()}</script>
  <script>
    mermaid.initialize({
      startOnLoad: true,
      theme: window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'default',
    });
  </script>
</body>
</html>
`;
};
